const screens={welcome:document.getElementById('welcome'),interview:document.getElementById('interview'),result:document.getElementById('result'),farewell:document.getElementById('farewell')};
const questions=[
{kicker:'TU RITMO',text:'¿Cómo vives normalmente la tecnología?',options:[['Creo y produzco','Trabajo, edito y organizo varias cosas a la vez.','fold',3],['Con estilo propio','Me importa que cada dispositivo exprese mi personalidad.','flip',3],['Siempre conectado','Busco información y experiencias sin mirar una pantalla.','glasses',3],['En movimiento','La salud, el rendimiento y el seguimiento diario son esenciales.','watch',3]]},
{kicker:'TU PANTALLA',text:'¿Qué experiencia visual te emociona más?',options:[['Una pantalla que se transforma','Grande para trabajar y disfrutar contenido.','fold',3],['Una pantalla compacta y expresiva','Pequeña cuando la guardo, protagonista cuando la uso.','flip',3],['Información integrada en mi entorno','Tecnología que acompaña mi mirada.','glasses',3],['Datos claros de un vistazo','Lo importante siempre en mi muñeca.','watch',3]]},
{kicker:'TU MOMENTO',text:'Tienes una hora libre. ¿Qué haces?',options:[['Editar y avanzar un proyecto','Aprovecho cada minuto para crear algo.','fold',2],['Grabar fotos y videos','Busco un ángulo diferente y compartible.','flip',2],['Explorar un lugar nuevo','Quiero instrucciones y contexto sin distraerme.','glasses',2],['Entrenar o caminar','Me motiva ver mi progreso en tiempo real.','watch',2]]},
{kicker:'TU SUPERPODER',text:'¿Qué valoras más en un dispositivo?',options:[['Productividad inmersiva','Que se adapte a tareas grandes y complejas.','fold',3],['Portabilidad creativa','Que sea compacto, distinto y divertido.','flip',3],['Interacción natural','Que la tecnología se sienta menos visible.','glasses',3],['Bienestar inteligente','Que me ayude a conocer mejor mi cuerpo y rutina.','watch',3]]},
{kicker:'TU ESTILO',text:'¿Cómo quieres que te recuerden?',options:[['Como quien convierte ideas en resultados','Estrategia, ejecución y visión.','fold',2],['Como alguien auténtico e inesperado','Personalidad, color y espontaneidad.','flip',2],['Como quien siempre mira hacia adelante','Curiosidad y nuevas posibilidades.','glasses',2],['Como una persona constante','Equilibrio, disciplina y evolución.','watch',2]]},
{kicker:'TU FUTURO',text:'Elige la frase que mejor te representa.',options:[['Quiero hacer más sin limitarme','Mi dispositivo debe crecer conmigo.','fold',4],['Quiero vivir la tecnología a mi manera','No sigo formatos: los transformo.','flip',4],['Quiero descubrir una nueva forma de ver el mundo','La innovación debe sentirse natural.','glasses',4],['Quiero conocerme mejor cada día','Los pequeños avances construyen grandes cambios.','watch',4]]}
];
const results={
fold:{name:'Galaxy Z Fold8',tagline:'La productividad es tu superpoder.',description:'Combinas visión, creatividad y ejecución. Tu Galaxy ideal transforma una pantalla compacta en un espacio inmersivo para crear, trabajar y disfrutar contenido en grande.',className:'fold'},
flip:{name:'Galaxy Z Flip8',tagline:'Tu estilo no cabe en un formato convencional.',description:'Vives la tecnología con personalidad y espontaneidad. Tu Galaxy ideal es compacto, expresivo y está preparado para capturar cada momento desde una perspectiva distinta.',className:'flip'},
glasses:{name:'Galaxy Glasses',tagline:'Tu curiosidad cambia la forma de mirar el mundo.',description:'Buscas experiencias naturales, conectadas y futuristas. Tu Galaxy ideal integra información y descubrimiento sin alejarte de lo que sucede frente a ti.',className:'glasses'},
watch:{name:'Galaxy Watch',tagline:'Tu constancia convierte datos en evolución.',description:'Te mueve el equilibrio entre bienestar, rendimiento y conexión. Tu Galaxy ideal acompaña cada paso y convierte tu rutina diaria en información útil.',className:'watch'}
};
let current=0,scores={fold:0,flip:0,glasses:0,watch:0},selections=[];
const qText=document.getElementById('questionText'),qKicker=document.getElementById('questionKicker'),answers=document.getElementById('answers'),progressText=document.getElementById('progressText'),progressBar=document.getElementById('progressBar'),backBtn=document.getElementById('backBtn'),toast=document.getElementById('toast');
function showScreen(name){Object.entries(screens).forEach(([key,el])=>el.classList.toggle('active',key===name));window.scrollTo(0,0)}
function renderQuestion(){const q=questions[current];qKicker.textContent=q.kicker;qText.textContent=q.text;progressText.textContent=`${String(current+1).padStart(2,'0')} / ${String(questions.length).padStart(2,'0')}`;progressBar.style.width=`${((current+1)/questions.length)*100}%`;backBtn.style.visibility=current===0?'hidden':'visible';answers.innerHTML='';q.options.forEach(([title,detail,type,points],index)=>{const b=document.createElement('button');b.className='answer';b.type='button';b.innerHTML=`<strong>${title}</strong><span>${detail}</span>`;b.onclick=()=>choose(index,type,points);answers.appendChild(b)})}
function choose(index,type,points){selections[current]={index,type,points};scores[type]+=points;if(current<questions.length-1){current++;renderQuestion()}else showResult()}
function winningType(){return Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0]}
function showResult(){const type=winningType(),data=results[type];document.getElementById('resultName').textContent=data.name;document.getElementById('resultTagline').textContent=`“${data.tagline}”`;document.getElementById('resultDescription').textContent=data.description;document.getElementById('deviceArt').className=`device-art ${data.className}`;showScreen('result')}
function goBack(){if(current===0)return;const previous=selections[current-1];if(previous)scores[previous.type]-=previous.points;selections[current-1]=undefined;current--;renderQuestion()}
function reset(){current=0;scores={fold:0,flip:0,glasses:0,watch:0};selections=[];renderQuestion()}
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line.trim(),x,y);line=word+' ';y+=lineHeight}else line=test}ctx.fillText(line.trim(),x,y)}
function drawCover(){const c=document.getElementById('coverCanvas'),ctx=c.getContext('2d'),type=winningType(),d=results[type];const bg=ctx.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,'#071d42');bg.addColorStop(.55,'#020612');bg.addColorStop(1,'#09264d');ctx.fillStyle=bg;ctx.fillRect(0,0,1080,1350);ctx.fillStyle='#58baff';ctx.font='600 28px Arial';ctx.fillText('TU GALAXY IDEAL',74,92);ctx.fillStyle='#fff';ctx.font='700 92px Arial';wrapText(ctx,d.name,74,220,850,98);ctx.fillStyle='#dbe8f7';ctx.font='400 39px Arial';wrapText(ctx,`“${d.tagline}”`,74,445,780,52);ctx.fillStyle='#b7c5d8';ctx.font='400 30px Arial';wrapText(ctx,d.description,74,920,900,44);ctx.strokeStyle='rgba(255,255,255,.18)';ctx.beginPath();ctx.moveTo(74,1240);ctx.lineTo(1006,1240);ctx.stroke();ctx.fillStyle='#fff';ctx.font='600 24px Arial';ctx.fillText('GALAXY INSIDER',74,1293);ctx.fillStyle='#7f91aa';ctx.fillText('LONDRES 2026',820,1293);return c}
document.getElementById('startBtn').onclick=()=>{reset();showScreen('interview')};backBtn.onclick=goBack;document.getElementById('restartBtn').onclick=()=>{reset();showScreen('interview')};document.getElementById('finishBtn').onclick=()=>showScreen('welcome');
document.getElementById('downloadBtn').onclick=()=>{const c=drawCover(),a=document.createElement('a');a.download='mi-portada-galaxy-insider.png';a.href=c.toDataURL('image/png');a.click();notify('Portada guardada');setTimeout(()=>showScreen('farewell'),900)};
document.getElementById('shareBtn').onclick=async()=>{const d=results[winningType()],text=`Mi Galaxy ideal es ${d.name}: ${d.tagline} #GalaxyInsider`;try{if(navigator.share)await navigator.share({title:'Galaxy Insider',text});else{await navigator.clipboard.writeText(text);notify('Resultado copiado')}setTimeout(()=>showScreen('farewell'),700)}catch(e){}};
renderQuestion();
